from __future__ import annotations

from argparse import ArgumentParser
from pathlib import Path
import json
import time

from app.models.runs import CreatedAsset, Manifest, TaskPacket
from app.services.utils import atomic_write_json


def main() -> int:
    parser = ArgumentParser()
    parser.add_argument("--task-packet", required=True)
    parser.add_argument("--run-dir", required=True)
    parser.add_argument("--project-root", required=True)
    args = parser.parse_args()

    packet_path = Path(args.task_packet)
    run_dir = Path(args.run_dir)
    project_root = Path(args.project_root)
    packet = TaskPacket.model_validate(json.loads(packet_path.read_text(encoding="utf-8")))

    result_dir = project_root / "results" / packet.card_id / packet.task_id
    result_dir.mkdir(parents=True, exist_ok=True)

    print(f"[worker] starting {packet.task_id}", flush=True)
    time.sleep(0.1)
    print("[worker] writing summary", flush=True)
    summary_path = result_dir / "summary.md"
    summary_path.write_text(
        f"# {packet.card_id}\n\n{packet.goal}\n\nInputs: {len(packet.input_assets)}\n",
        encoding="utf-8",
    )
    time.sleep(0.1)
    print("[worker] writing table", flush=True)
    table_path = result_dir / "result.tsv"
    table_path.write_text("feature\tscore\nterm_1\t0.91\nterm_2\t0.84\n", encoding="utf-8")
    time.sleep(0.1)
    print("[worker] writing preview", flush=True)
    plot_path = result_dir / "preview.svg"
    plot_path.write_text(
        "\n".join(
            [
                "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 720 320'>",
                "  <rect width='720' height='320' fill='#0f1724' />",
                "  <rect x='48' y='56' width='620' height='220' rx='18' fill='#122031' stroke='#35506d' />",
                "  <text x='72' y='96' fill='#edf2fb' font-size='24' font-family='Arial'>Synthetic Preview</text>",
                "  <text x='72' y='128' fill='#9cb0cd' font-size='15' font-family='Arial'>Generated by demo executor</text>",
                "  <polyline fill='none' stroke='#4a8cff' stroke-width='6' points='92,232 184,198 276,210 368,148 460,164 552,118 644,134' />",
                "  <circle cx='184' cy='198' r='6' fill='#f0af44' />",
                "  <circle cx='368' cy='148' r='6' fill='#3fb37b' />",
                "  <circle cx='552' cy='118' r='6' fill='#ef5f67' />",
                "</svg>",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    transcript_path = run_dir / "transcript.md"
    transcript_path.write_text(
        "\n".join(
            [
                f"# {packet.task_id}",
                "",
                "Executor transcript",
                "- started local scaffold execution",
                "- wrote summary/table/preview assets",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    manifest = Manifest(
        run_id=packet.task_id,
        status="success",
        summary="Local scaffold worker completed successfully.",
        inputs_used=packet.input_assets,
        created_assets=[
            CreatedAsset(
                role="summary",
                type="markdown",
                path=str(summary_path.relative_to(project_root)),
                description="Summary output.",
            ),
            CreatedAsset(
                role="table",
                type="table",
                path=str(table_path.relative_to(project_root)),
                description="Primary result table.",
            ),
            CreatedAsset(
                role="plot",
                type="figure",
                path=str(plot_path.relative_to(project_root)),
                description="Preview figure.",
            ),
        ],
        commands_executed=["demo_executor"],
        metrics={"synthetic_score": 0.91, "asset_count": 3},
        key_findings=["Generated representative downstream result set."],
        recommended_graph_updates=[
            {"op": "create_asset", "asset_type": "markdown"},
            {"op": "create_asset", "asset_type": "table"},
            {"op": "create_asset", "asset_type": "figure"},
        ],
        warnings=[],
    )
    atomic_write_json(run_dir / "manifest.json", manifest.model_dump())
    print("[worker] manifest complete", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
