export const queryKeys = {
  projects: ["projects"] as const,
  appSettings: ["app-settings"] as const,
  executorProfiles: ["executor-profiles"] as const,
  library: (kind: "skill" | "mcp") => ["library", kind] as const,
  projectSkillLibrary: (projectId: string) => ["project-skill-library", projectId] as const,
  projectMcpLibrary: (projectId: string) => ["project-mcp-library", projectId] as const,
  project: (projectId: string) => ["project", projectId] as const,
  projectEnvironment: (projectId: string) => ["project-environment", projectId] as const,
  managerAuto: (projectId: string, sessionId?: string | null) => ["manager-auto", projectId, sessionId ?? "none"] as const,
  chatSessions: (projectId: string) => ["chat-sessions", projectId] as const,
  chatSession: (projectId: string, sessionId: string) => ["chat-session", projectId, sessionId] as const,
  assetFlow: (projectId: string) => ["asset-flow", projectId] as const,
  workOrder: (projectId: string) => ["work-order", projectId] as const,
  results: (projectId: string) => ["results", projectId] as const,
  files: (projectId: string) => ["files", projectId] as const,
  resultAsset: (projectId: string, assetId: string) => ["result-asset", projectId, assetId] as const,
  report: (projectId: string) => ["report", projectId] as const,
  advancedGraph: (projectId: string) => ["advanced-graph", projectId] as const,
  advancedGit: (projectId: string) => ["advanced-git", projectId] as const,
  advancedProposals: (projectId: string) => ["advanced-proposals", projectId] as const,
  runEvents: (projectId: string, runId: string) => ["run-events", projectId, runId] as const,
  runtimeApprovals: (projectId: string, runId: string) => ["runtime-approvals", projectId, runId] as const,
};
